# Constant values
WATER_VALUE = 6
FOOD_VALUE = 30
MEDICAL_VALUE = 50
CANTEEN_VALUE = 15
BASE_DAMAGE = 10
CAREER_BONUS = 5
MALE_BONUS = 5
TURNS_PER_DAY = 48
BASE_SPEED = 1
# SLEEP_CAP
SLEEP_VALUE = 5
DAMAGE_MULTIPLIER = 0.5 # how much the tribute's strength impacts how strong their attack is
SMALL_BACKPACK_FOOD = 3
SMALL_BACKPACK_MED = 0
LARGE_BACKPACK_FOOD = 5
LARGE_BACKPACK_MED = 2
LARGE_CAPACITY = 10
SMALL_CAPACITY = 5
STRONG_WEAPON = 40
WEAK_WEAPON = 20
MUTT_STRENGTH = 50


STRENGTH_BY_AGE = {
    12: (10, 15),
    13: (10, 15),
    14: (15, 20),
    15: (15, 20),
    16: (20, 25),
    17: (20, 25),
    18: (25, 30)
}

# Stat impact constants
THIRST_WARNING_THRESHOLD = 50
THIRST_DECAY = 0.52
THIRST_WARNING_PENALTY = 1
THIRST_HEALTH_PENALTY = 20

HUNGER_WARNING_THRESHOLD = 50
HUNGER_DECAY = 0.42
HUNGER_WARNING_PENALTY = 1
HUNGER_HEALTH_PENALTY = 15


# Rewards
DRINK_REWARD = 3.0
EAT_REWARD = 5.0
REFILL_REWARD = 3.0
MEDICAL_REWARD = 1.0
ATTACK_REWARD = 2.0
PICKUP_REWARD = 3.0
MOVE_REWARD = .001
WIN_ATTACK_REWARD = 2.0
KILL_REWARD = 15
FOOD_PICKUP_REWARD = 2.0




# Gamemaker influence
BOMB_DAMAGE_NEAR = -30
BOMB_DAMAGE_FAR = -10



